### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by JedLJRobertson** [SE701ProjectGroup4/Flatmate-Management-System#9]
As a Developer, I want a way to make sure that new issues are created in a standardised format so that it is easy to find what the issue is.

Acceptance Criteria:
 - The format is documented on Github wiki

From Hong

**Comment by HongShi10** [comment]
I should feel like we have a template for all the issues that are being created. An example of this issue is below.

As a Developer, I want a way to make sure that new issues are created in a standardised format so that it is easy to find what the issue is.

Acceptance Criteria
- The format is documented on Github wiki

**Comment by jhsi517** [comment]
Perhaps I should add this in to the contribution doc?
